# Generated by Django 6.0.3 on 2026-06-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_number',
            field=models.PositiveIntegerField(),
        ),
    ]
